### ISSUE TITLE
Is there a release scheduled soon?

### ISSUE THREAD

**Issue by Nimamoh** [srwalter/dbus-serialize#5]
Hello,

I wondered if there would be a release soon.
I noticed at least one feature on master that could be interesting to be pushed: 

https://github.com/srwalter/dbus-serialize/commit/5cfbf746262718675a7b3442e59bb0448fb305ea

Thanks in advance.

**Comment by srwalter** [comment]
Sorry for the wait, but I've published new releases of dbus-serialize and dbus-bytestream to crates.io
